import Head from "next/head";
import Image from "next/image";
import axios from "axios";
import { useState } from "react";
import { BsSearch } from "react-icons/bs";
import DataWeather from "../components/DataWeather";

export default function Home() {
  const [city, SetCity] = useState("");
  const [weather, setWeather] = useState({});
  const [loading, setLoading] = useState(false);

  const url = `https://api.openweathermap.org/data/2.5/weather?q=${city}&units=imperial&appid=${process.env.NEXT_PUBLIC_WEATHER_KEY}`;

  const fetchWeather = (e) => {
    e.preventDefault();
    setLoading(true);
    axios.get(url).then((response) => {
      setWeather(response.data);
    });
    SetCity("");
    setLoading(false);
  };
  return (
    <div>
      <Head>
        <title>Weather WebApp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className=" absolute top-0 bottom-0 right-0 left-0" />

      <Image
        src="https://images.unsplash.com/photo-1542272201-b1ca555f8505?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=987&q=80"
        layout="fill"
      />
      <div className=" relative flex justify-between items-center max-w-[500px] w-full m-auto pt-5 text-black z-10 mt-10">
        <form
          onSubmit={fetchWeather}
          className=" flex justify-between items-center p-5 bg-transparent w-full m-auto rounded-3xl text-black border border-stone-900"
        >
          <div>
            <input
              onChange={(e) => SetCity(e.target.value)}
              className=" bg-transparent focus:outline-none font-bold text-black tracking-widest border-none text-sm placeholder:text-black"
              type="text"
              placeholder="SEARCH CITY"
            />
          </div>
          <button onClick={fetchWeather}>
            <BsSearch size={15} />
          </button>
        </form>
      </div>

      <div>{weather.main && <DataWeather data={weather} />}</div>
    </div>
  );
}
